name: Manual trigger

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: saludo
        run: echo "hello"
        
